name: Test Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build container
        run: |
          docker build -t micro-api-core . 
          heroku container:push -a micro-api-core web
